//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5485
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
[System.Xml.Serialization.XmlRootAttribute("researchOrder", Namespace="http://kiminoboku.pl/emorg", IsNullable=false)]
public partial class ResearchOrder {
    
    private Research researchField;
    
    private string researchLogIdField;
    
    /// <uwagi/>
    public Research research {
        get {
            return this.researchField;
        }
        set {
            this.researchField = value;
        }
    }
    
    /// <uwagi/>
    public string researchLogId {
        get {
            return this.researchLogIdField;
        }
        set {
            this.researchLogIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class Research {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    private string descriptionField;
    
    private AbstractOperation[] operationsField;
    
    /// <uwagi/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <uwagi/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayItemAttribute("operation", IsNullable=false)]
    public AbstractOperation[] operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
}

/// <uwagi/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TerminateCommandOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextMessageOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SleepOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagePeripheralsOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RunCommandOperation))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public abstract partial class AbstractOperation {
    
    private int orderNumberField;
    
    private bool orderNumberFieldSpecified;
    
    private OperationType operationTypeField;
    
    private string xmlReferenceIdField;
    
    /// <uwagi/>
    public int orderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderNumberSpecified {
        get {
            return this.orderNumberFieldSpecified;
        }
        set {
            this.orderNumberFieldSpecified = value;
        }
    }
    
    /// <uwagi/>
    public OperationType operationType {
        get {
            return this.operationTypeField;
        }
        set {
            this.operationTypeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
    public string xmlReferenceId {
        get {
            return this.xmlReferenceIdField;
        }
        set {
            this.xmlReferenceIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public enum OperationType {
    
    /// <uwagi/>
    MANAGE_PERIPHERALS,
    
    /// <uwagi/>
    SLEEP,
    
    /// <uwagi/>
    TEXT_MESSAGE,
    
    /// <uwagi/>
    RUN_COMMAND,
    
    /// <uwagi/>
    TERMINATE_COMMAND,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class TerminateCommandOperation : AbstractOperation {
    
    private string commandToTerminateIdField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="IDREF")]
    public string commandToTerminateId {
        get {
            return this.commandToTerminateIdField;
        }
        set {
            this.commandToTerminateIdField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class TextMessageOperation : AbstractOperation {
    
    private string messageTitleField;
    
    private string messageContentField;
    
    /// <uwagi/>
    public string messageTitle {
        get {
            return this.messageTitleField;
        }
        set {
            this.messageTitleField = value;
        }
    }
    
    /// <uwagi/>
    public string messageContent {
        get {
            return this.messageContentField;
        }
        set {
            this.messageContentField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class SleepOperation : AbstractOperation {
    
    private int sleepTimeSecondsField;
    
    /// <uwagi/>
    public int sleepTimeSeconds {
        get {
            return this.sleepTimeSecondsField;
        }
        set {
            this.sleepTimeSecondsField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class ManagePeripheralsOperation : AbstractOperation {
    
    private PeripheralStateChange mouseStateChangeField;
    
    private PeripheralStateChange keyboardStateChangeField;
    
    /// <uwagi/>
    public PeripheralStateChange mouseStateChange {
        get {
            return this.mouseStateChangeField;
        }
        set {
            this.mouseStateChangeField = value;
        }
    }
    
    /// <uwagi/>
    public PeripheralStateChange keyboardStateChange {
        get {
            return this.keyboardStateChangeField;
        }
        set {
            this.keyboardStateChangeField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public enum PeripheralStateChange {
    
    /// <uwagi/>
    TURN_ON,
    
    /// <uwagi/>
    TURN_OFF,
    
    /// <uwagi/>
    DO_NOTHING,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class RunCommandOperation : AbstractOperation {
    
    private string commandField;
    
    /// <uwagi/>
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
}
