//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
[System.Xml.Serialization.XmlRootAttribute("researchOrder", Namespace="http://kiminoboku.pl/emorg", IsNullable=false)]
public partial class ResearchOrder {
    
    private Research researchField;
    
    private string researchLogIdField;
    
    /// <remarks/>
    public Research research {
        get {
            return this.researchField;
        }
        set {
            this.researchField = value;
        }
    }
    
    /// <remarks/>
    public string researchLogId {
        get {
            return this.researchLogIdField;
        }
        set {
            this.researchLogIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class Research {
    
    private AbstractOperation[] operationsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("operation", IsNullable=false)]
    public AbstractOperation[] operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextMessageOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SleepOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagePeripheralsOperation))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RunCommandOperation))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public abstract partial class AbstractOperation {
    
    private OperationType operationTypeField;
    
    /// <remarks/>
    public OperationType operationType {
        get {
            return this.operationTypeField;
        }
        set {
            this.operationTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public enum OperationType {
    
    /// <remarks/>
    MANAGE_PERIPHERALS,
    
    /// <remarks/>
    SLEEP,
    
    /// <remarks/>
    TEXT_MESSAGE,
    
    /// <remarks/>
    RUN_COMMAND,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class TextMessageOperation : AbstractOperation {
    
    private string messageTitleField;
    
    private string messageContentField;
    
    /// <remarks/>
    public string messageTitle {
        get {
            return this.messageTitleField;
        }
        set {
            this.messageTitleField = value;
        }
    }
    
    /// <remarks/>
    public string messageContent {
        get {
            return this.messageContentField;
        }
        set {
            this.messageContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class SleepOperation : AbstractOperation {
    
    private int sleepTimeSecondsField;
    
    /// <remarks/>
    public int sleepTimeSeconds {
        get {
            return this.sleepTimeSecondsField;
        }
        set {
            this.sleepTimeSecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class ManagePeripheralsOperation : AbstractOperation {
    
    private PeripheralStateChange mouseStateChangeField;
    
    private PeripheralStateChange keyboardStateChangeField;
    
    /// <remarks/>
    public PeripheralStateChange mouseStateChange {
        get {
            return this.mouseStateChangeField;
        }
        set {
            this.mouseStateChangeField = value;
        }
    }
    
    /// <remarks/>
    public PeripheralStateChange keyboardStateChange {
        get {
            return this.keyboardStateChangeField;
        }
        set {
            this.keyboardStateChangeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public enum PeripheralStateChange {
    
    /// <remarks/>
    TURN_ON,
    
    /// <remarks/>
    TURN_OFF,
    
    /// <remarks/>
    DO_NOTHING,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kiminoboku.pl/emorg")]
public partial class RunCommandOperation : AbstractOperation {
    
    private string commandField;
    
    /// <remarks/>
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
}
