/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.kiminoboku.netbeans;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//pl.kiminoboku.netbeans//ManagePeripherals//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ManagePeripheralsTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "pl.kiminoboku.netbeans.ManagePeripheralsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ManagePeripheralsAction",
        preferredID = "ManagePeripheralsTopComponent"
)
@Messages({
    "CTL_ManagePeripheralsAction=Manage peripherals",
    "CTL_ManagePeripheralsTopComponent=Manage peripherals window",
    "HINT_ManagePeripheralsTopComponent=This is a Manage peripherals window"
})
public final class ManagePeripheralsTopComponent extends TopComponent {

    public ManagePeripheralsTopComponent() {
        initComponents();
        setName(Bundle.CTL_ManagePeripheralsTopComponent());
        setToolTipText(Bundle.HINT_ManagePeripheralsTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mouseJLabel = new javax.swing.JLabel();
        keyboardJLabel = new javax.swing.JLabel();
        mouseOnJButton = new javax.swing.JButton();
        mouseOffJButton = new javax.swing.JButton();
        keyboardOnJButton = new javax.swing.JButton();
        keyboardOffJButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(mouseJLabel, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.mouseJLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(keyboardJLabel, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.keyboardJLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mouseOnJButton, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.mouseOnJButton.text")); // NOI18N
        mouseOnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseOnJButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(mouseOffJButton, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.mouseOffJButton.text")); // NOI18N
        mouseOffJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseOffJButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(keyboardOnJButton, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.keyboardOnJButton.text")); // NOI18N
        keyboardOnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardOnJButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(keyboardOffJButton, org.openide.util.NbBundle.getMessage(ManagePeripheralsTopComponent.class, "ManagePeripheralsTopComponent.keyboardOffJButton.text")); // NOI18N
        keyboardOffJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardOffJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyboardJLabel)
                    .addComponent(mouseJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mouseOnJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mouseOffJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keyboardOnJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyboardOffJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {keyboardOffJButton, keyboardOnJButton, mouseOffJButton, mouseOnJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mouseJLabel)
                    .addComponent(mouseOffJButton)
                    .addComponent(mouseOnJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyboardJLabel)
                    .addComponent(keyboardOnJButton)
                    .addComponent(keyboardOffJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseOnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseOnJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseOnJButtonActionPerformed

    private void mouseOffJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseOffJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseOffJButtonActionPerformed

    private void keyboardOnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardOnJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyboardOnJButtonActionPerformed

    private void keyboardOffJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardOffJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyboardOffJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel keyboardJLabel;
    private javax.swing.JButton keyboardOffJButton;
    private javax.swing.JButton keyboardOnJButton;
    private javax.swing.JLabel mouseJLabel;
    private javax.swing.JButton mouseOffJButton;
    private javax.swing.JButton mouseOnJButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
