/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.kiminoboku.netbeans.research.edit;

import java.awt.event.ActionEvent;
import java.io.IOException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.spi.actions.AbstractSavable;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.Actions;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;
import pl.kiminoboku.emorg.service.ServiceFactory;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//pl.kiminoboku.netbeans.research.edit//EditResearch//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "EditResearchTopComponent",
        iconBase = "icons/research/new-research_16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = EditResearchTopComponent.ACTION_CATEGORY, id = EditResearchTopComponent.ACTION_ID)
@ActionReference(path = "Menu/File", position = 0)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EditResearchAction")
@Messages({
    "CTL_EditResearchAction=New research",
    "CTL_EditResearchTopComponent=New research {0}",
    "HINT_EditResearchTopComponent=Research data"
})
public final class EditResearchTopComponent extends TopComponent {

    public static final String ACTION_CATEGORY = "Window";

    public static final String ACTION_ID = "pl.kiminoboku.netbeans.research.edit.EditResearchTopComponent";

    public static void openNew(ActionEvent evt) {
        Actions.forID(ACTION_CATEGORY, ACTION_ID).actionPerformed(evt);
    }
    private InstanceContent instanceContent;

    private SaveHandler saveHandler;

    public EditResearchTopComponent() {
        initComponents();
        long counter = ServiceFactory.getObjectCounterService().getNext();
        String name = Bundle.CTL_EditResearchTopComponent(counter);
        setName(name);
        editResearchHeader.setNameText(name);
        editResearchHeader.setDescriptionText("");
        setToolTipText(Bundle.HINT_EditResearchTopComponent());
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        editResearchHeader.addDocumentListener(new ModifyHeaderListener());
        operationListJPanel.addListDataListener(new ModifyOperationsListListener());

        instanceContent = new InstanceContent();
        associateLookup(new AbstractLookup(instanceContent));
        saveHandler = new SaveHandler();
    }

    private void setModified(boolean newModified) {
        if (newModified) {
            setName("<html><b>" + editResearchHeader.getNameText() + "</b></html>");
        } else {
            setName(editResearchHeader.getNameText());
        }

        saveHandler.setSaveEnabled(newModified);
    }

    private boolean isModified() {
        return saveHandler.isSaveEnabled();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        editResearchHeader = new pl.kiminoboku.netbeans.research.edit.EditResearchHeader();
        jScrollPane1 = new javax.swing.JScrollPane();
        operationListJPanel = new pl.kiminoboku.netbeans.research.edit.OperationListJPanel();

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setTopComponent(editResearchHeader);

        jScrollPane1.setViewportView(operationListJPanel);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.kiminoboku.netbeans.research.edit.EditResearchHeader editResearchHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private pl.kiminoboku.netbeans.research.edit.OperationListJPanel operationListJPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public boolean canClose() {
        if (isModified()) {
            String message = NbBundle.getMessage(EditResearchTopComponent.class, "EditResearchTopComponent.unsavedChanges", editResearchHeader.getNameText());
            Object answer = DialogDisplayer.getDefault().notify(new NotifyDescriptor.Confirmation(message));
            if (answer == NotifyDescriptor.YES_OPTION) {
                return saveResearch();
            } else if (answer == NotifyDescriptor.NO_OPTION) {
                setModified(false);
            }
            return answer != NotifyDescriptor.CANCEL_OPTION;
        }
        return true;
    }

    private boolean saveResearch() {
        //FIXME invoke save logic, return save result
        DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message("Invoke save logic"));
        setModified(false);
        return true;
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        // TODO read your settings according to their version
    }

    private class ModifyHeaderListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            setModified(true);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            setModified(true);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            setModified(true);
        }
    }

    private class ModifyOperationsListListener implements ListDataListener {

        @Override
        public void intervalAdded(ListDataEvent e) {
            setModified(true);
        }

        @Override
        public void intervalRemoved(ListDataEvent e) {
            setModified(true);
        }

        @Override
        public void contentsChanged(ListDataEvent e) {
            setModified(true);
        }
    }

    private class SaveHandler extends AbstractSavable {

        private boolean saveEnabled;

        @Override
        protected String findDisplayName() {
            return NbBundle.getMessage(EditResearchTopComponent.class, "EditResearchTopComponent.researchDescription", editResearchHeader.getNameText());
        }

        @Override
        protected void handleSave() throws IOException {
            saveResearch();
        }

        public boolean isSaveEnabled() {
            return saveEnabled;
        }

        public void setSaveEnabled(boolean saveEnabled) {
            if (saveEnabled != this.saveEnabled) {
                this.saveEnabled = saveEnabled;
                if (saveEnabled) {
                    instanceContent.add(this);
                    register();
                } else {
                    instanceContent.remove(this);
                    unregister();
                }
            }
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            SaveHandler other = (SaveHandler) obj;
            return tc().equals(other.tc());
        }

        @Override
        public int hashCode() {
            return tc().hashCode();
        }

        private EditResearchTopComponent tc() {
            return EditResearchTopComponent.this;
        }
    }
}
