/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.kiminoboku.netbeans.components.operation;

import javax.swing.Icon;

/**
 *
 * @author Radek
 */
public class OperationRowJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OperationRowJPanel
     */
    public OperationRowJPanel() {
        initComponents();
    }

    public String getDescriptionLabelText() {
        return descriptionLabel.getText();
    }

    public void setDescriptionLabelText(String descriptionLabelText) {
        descriptionLabel.setText(descriptionLabelText);
    }

    public String getNumberLabelText() {
        return numberLabel.getText();
    }

    public void setNumberLabelText(String numberLabelText) {
        numberLabel.setText(numberLabelText);
    }

    public Icon getIcon() {
        return operationIcon.getIcon();
    }

    public void setIcon(Icon icon) {
        operationIcon.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        operationIcon = new pl.kiminoboku.netbeans.components.IconComponent();
        descriptionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        settingsButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addAboveButton = new javax.swing.JButton();
        addBelowButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(32767, 73));
        setMinimumSize(new java.awt.Dimension(506, 73));

        org.openide.awt.Mnemonics.setLocalizedText(numberLabel, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.numberLabel.text")); // NOI18N
        numberLabel.setMaximumSize(new java.awt.Dimension(18, 14));
        numberLabel.setMinimumSize(new java.awt.Dimension(18, 14));
        numberLabel.setPreferredSize(new java.awt.Dimension(18, 14));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        operationIcon.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanel1.add(operationIcon, new java.awt.GridBagConstraints());

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(descriptionLabel, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.descriptionLabel.text")); // NOI18N

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(settingsButton, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.settingsButton.text")); // NOI18N
        jPanel2.add(settingsButton);

        org.openide.awt.Mnemonics.setLocalizedText(removeButton, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.removeButton.text")); // NOI18N
        jPanel2.add(removeButton);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(addAboveButton, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.addAboveButton.text")); // NOI18N
        jPanel3.add(addAboveButton);

        org.openide.awt.Mnemonics.setLocalizedText(addBelowButton, org.openide.util.NbBundle.getMessage(OperationRowJPanel.class, "OperationRowJPanel.addBelowButton.text")); // NOI18N
        jPanel3.add(addBelowButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAboveButton;
    private javax.swing.JButton addBelowButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numberLabel;
    private pl.kiminoboku.netbeans.components.IconComponent operationIcon;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
