CREATE ROLE emorg;
ALTER ROLE emorg WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md56bcc2b6ecdb2d09bd52f3d968dbd5283' VALID UNTIL 'infinity';

CREATE DATABASE "emorg-prod" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'Polish_Poland.1250' LC_CTYPE = 'Polish_Poland.1250';
ALTER DATABASE "emorg-prod" OWNER TO emorg;